workflows:
  flutter-ios-android-release:
    name: Kivo Super App Release Pipeline
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
        - google_credentials
        - android_keystore
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate Flutter Native Boilerplate
        script: |
          cd mobile
          flutter create .
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mobile/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd mobile
          flutter packages pub get
      - name: Install iOS Pods
        script: |
          cd mobile/ios
          pod install
      - name: Build iOS App (IPA)
        script: |
          cd mobile
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
      - name: Build Android App Bundle (AAB)
        script: |
          cd mobile
          flutter build appbundle --release
    artifacts:
      - mobile/build/ios/ipa/*.ipa
      - mobile/build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - yourmail@example.com # Update this in Codemagic UI
        notify:
          success: true
          failure: true
      # Uploads to TestFlight using the keys from the 'apple_credentials' group
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      # Uploads to Google Play using the keys from the 'google_credentials' group
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
