name: kivo
description: A closed-loop Super App for the Jamaican market.
publish_to: 'none'

version: 1.0.22+157

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_messaging: ^15.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  provider: ^6.1.1
  youtube_player_flutter: ^9.0.3
  cached_network_image: ^3.3.0
  fl_chart: ^0.66.0
  local_auth: ^2.1.8
  sqflite: 2.3.3+1
  device_info_plus: ^9.1.1
  google_mobile_ads: ^5.1.0
  webview_flutter: ^4.7.0
  webview_flutter_wkwebview: ^3.13.0
  webview_flutter_android: ^3.15.0
  flutter_tts: ^4.2.2
  audioplayers: ^6.1.1
  image_picker: ^1.1.2
  youtube_player_iframe: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
